INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME) VALUES('nelson','mandela');
INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME) VALUES('abraham','lincoln');
INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME) VALUES('a.p.j.','abdul kalam');
INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME) VALUES('coco','chanel');
INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME) VALUES('anne','frank');
INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME) VALUES('albert','einstein');
INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME) VALUES('walt','disney');
INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME) VALUES('sachin','tendulkar');
INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME) VALUES('long','01234567890123456789');