DROP TABLE PEOPLE IF EXISTS;

CREATE TABLE PEOPLE  (
    PERSON_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20)
);


DROP TABLE PEOPLE_CONVERTED IF EXISTS;

CREATE TABLE PEOPLE_CONVERTED  (
                         PERSON_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
                         FIRST_NAME VARCHAR(20),
                         LAST_NAME VARCHAR(20)
);
